version: '3.1'
services:
  mongodb:
    image: mongo:4.4.0
    container_name: mongo
    environment:
        MONGO_INITDB_DATABASE: main
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
  crawler:
    build: .
    ports:
      - 6800:6800
    volumes:
      - .:/scrapy
    depends_on:
      - mongodb
    
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    volumes:
      - .:/bot
    depends_on:
      - mongodb
    
